# Generated by Django 5.2.4 on 2025-07-18 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('platform_id', models.IntegerField()),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('daily_connection_request', models.IntegerField(default=0)),
                ('weekly_connection_request_limit', models.IntegerField(default=0)),
                ('daily_connection_request_count', models.IntegerField(default=0)),
                ('weekly_connection_request_count', models.IntegerField(default=0)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        )
    ]
